services:
  mariadb:
    # https://hub.docker.com/r/bitnami/mariadb
    image: docker.io/bitnami/mariadb:11.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    networks:
      - wordpressnetwork

  wordpress:
    # https://hub.docker.com/r/bitnami/wordpress
    image: docker.io/bitnami/wordpress:6
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      # Do not mount the plugin when setting up the container for the first time,
      # because it will cause the WordPress setup to fail.
      - ./dist:/bitnami/wordpress/wp-content/plugins/shapediver-wordpress-plugin
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    networks:
      - wordpressnetwork

networks:
  wordpressnetwork:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
