version: '3'

services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=your_root_password
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bitnami_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - '3000:8080'
      - '443:8443'
    volumes:
      - wordpress_data:/bitnami/wordpress
      - apache_data:/bitnami/apache
      - ./plugin:/bitnami/wordpress/wp-content/plugins/shapediver-wordpress-plugin
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
